# Copyright 2023 Google LLC.
# SPDX-License-Identifier: Apache-2.0

apiVersion: batch/v1
kind: Job
metadata:
  name: agents
spec:
  parallelism: 2
  completions: 2
  completionMode: Indexed
  template:
    metadata:
      labels:
        task: simulation
    spec:
      subdomain: mysvc
      volumes:
      - name: script-volume
        configMap:
          name: agent-script
      containers:
      - name: main
        image: python:3.10.10-bullseye
        command: ["bash"]
        args:
        - -c
        - |
          pip install grpcio dm-env dm-env-rpc
          python /script-path/catch_ai_agent.py environments-$JOB_COMPLETION_INDEX.mysvc:12345 0.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /script-path
            name: script-volume
      restartPolicy: Never
  backoffLimit: 6
